sdnSite/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

###############################################################################
#   urlpatterns are the start of the chain fired off by django,
#   Use class_name.as_view() for class references from views.py, and use
#   views.method_name for method reference from views.py.
###############################################################################
urlpatterns = [
    # SDN.com/accounts/register/
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    # SDN.com/accounts/login_user/
    url(r'^login_user/$',views.LoginView.as_view(),name='login_user'),
    # SDN.com/accounts/logout_user
    url(r'^logout_user/$',views.LogoutView.as_view(),name='logout_user'),
	url(r'^upload_picture/$',views.uploadPicture,name='upload_picture'),
	url(r'^upload_resume/$',views.uploadResume,name='upload_resume'),
	# SDN.com/accounts/ ^(?P<profilename>)
    url(r'^$', views.AccountView.as_view(), name="account_page"),
]

sdnSite/home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # ex: /home/
    url(r'^$', views.IndexView.as_view(), name='index'),
    
]

sdnSite/posting/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.new_post, name="new_post"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^apply/$', views.application, name="application"),
    url(r'^congrats/$', views.congratulations, name="congrats"),
]

sdnSite/sdnSite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views
from posting import views
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^posting/', include('posting.urls', namespace='posting')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sdnSite/home/models.py
from django.db import models
from django.utils import timezone
#from accounts import UserProfile
#from posting import posting
# Create your models here.

class Member(models.Model):
	email = models.EmailField(primary_key=True)
	name = models.CharField(max_length=50)
	phone = models.IntegerField()
	address = models.CharField(max_length=50)
	biography = models.CharField(max_length=300)
	business = models.BooleanField(default=False)
	#Account links could become its own table to
	#ensure that the data entered remains atomic.

class Posting(models.Model):
	job_id = models.AutoField(primary_key=True);
	employer_id = models.ForeignKey(Member, on_delete=models.CASCADE)
	job_title = models.CharField(default="make an app", max_length=50)
	description = models.CharField(default="a decent job", max_length=1000)
	#status could be set up as a list of choices
	status = models.IntegerField(default=0)
	finish_date = models.DateTimeField(default=timezone.now)
	post_date = models.DateTimeField(default=timezone.now)

class Image(models.Model):
	image_id = models.IntegerField(primary_key=True)
	member_id = models.ForeignKey(Member,on_delete=models.CASCADE)
	#image_reference = models.ImageField() #lets just fill this attribute with image links
	title = models.CharField(max_length=30)

class File(models.Model):
	file_id = models.IntegerField(primary_key=True);
	business_id = models.ForeignKey(Member,on_delete=models.CASCADE)
	title = models.CharField(max_length=30)
	file_reference = models.CharField(max_length=100) #Assuming a web link

class Tag(models.Model):
	skill_id = models.AutoField(primary_key=True)
	skill_name = models.CharField(max_length=30)
	description = models.CharField(max_length=100)

	def __str__(self):
		return (self.skill_name)

class Job_Tag(models.Model):
	job_id = models.ForeignKey('posting.posting',on_delete=models.CASCADE)
	skill_id = models.ForeignKey(Tag,on_delete=models.CASCADE)

class Member_Tag(models.Model):
	member_id = models.ForeignKey('accounts.UserProfile',on_delete=models.CASCADE)
	skill_id = models.ForeignKey(Tag,on_delete=models.CASCADE)

class Review(models.Model):
	job_id = models.ForeignKey(Posting,on_delete=models.CASCADE)
	reviewer_id = models.ForeignKey(Member,on_delete=models.CASCADE)
	#reviewee_id = models.ForeignKey(Member,on_delete=models.CASCADE)

class Contract(models.Model):
	contract_id = models.IntegerField(primary_key=True)
	job_id = models.ForeignKey(Posting,on_delete=models.CASCADE)
	contractor_id = models.ForeignKey(Member, on_delete=models.CASCADE)
	deliverable = models.CharField(max_length=1000)
	total_pay = models.FloatField()
	percent_up_front = models.FloatField()
	create_date = models.DateTimeField(default=timezone.now)

class Application(models.Model):
	app_id = models.IntegerField(primary_key=True)
	job_id = models.ForeignKey(Posting)
	member_id = models.ForeignKey(Member)
	create_date = models.DateTimeField(default=timezone.now)
	cover_letter = models.CharField(max_length=1000)
	resume_id = models.ForeignKey(File)

sdnSite/home/views.py
from django.shortcuts import render, HttpResponse, render
from django.template import loader
from django.http import Http404
from django.views import generic
from django.views.generic import ListView, TemplateView
from django.db import models
from posting.models import posting


class IndexView(TemplateView):

    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['latest_posting_list'] = posting.objects.all()
        return context

# Create your views here.
def index(request):
    latest_posting_list = posting.objects.order_by('-pub_date')
    context = {'latest_posting_list': latest_posting_list}
    return render(request, 'home/index.html', context)


def worker(request):
    return render(request, 'home/worker.html')

def employer(request):
    return render(request, 'home/employer.html')

sdnSite/home/templates/home/base.html
<!-- This is the base html template used throughout the website, built on
     bootstrap. pages accessed with current user session will receive this navbar
     and page configuration -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SDN{% endblock %}</title>
    <!-- import django static files from ../static/ -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'home/home.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home:index' %}">Freelance Connect</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                  <li>
                      <a href="{% url 'accounts:account_page' %}">My Account</a>
                  </li>
                  <li>
                      <a href="{% url 'posting:new_post' %}">Post</a>
                  </li>
                  <li>
                      <a href="{% url 'accounts:logout_user' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="{% block register_active %}{% endblock %}">
                    <a href="{% url 'accounts:register' %}">Sign Up</a>
                  </li>
                  <li class="{% block login_active %}{% endblock %}">
                    <a href="{% url 'accounts:login_user' %}">Log In</a>
                  </li>
                {% endif %}

              </ul>
              <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'home:index' %}">
               <div class="form-group">
                   <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
               </div>
               <button type="submit" class="btn btn-default">Search</button>
              </form>
              {% if user.is_authenticated %}
              <div class="pull-right">
                <ul class="nav pull-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{ user.username }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/user/preferences"><i class="icon-cog"></i> Preferences</a></li>
                            <li><a href="/help/support"><i class="icon-envelope"></i> Contact Support</a></li>
                            <li class="divider"></li>
                            <li><a href="/auth/logout"><i class="icon-off"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
              </div>
              {% endif %}
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>
  {% block body %}
  <!-- this is page specific html area -->
  {% endblock %}
</body>
</html>

sdnSite/home/templates/home/index.html
<!--  -->


{% extends 'home/base.html' %}

{% block title %}Latest Postings{% endblock %}
{% block index_active %}active{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
<style>
              body { background-color: LightGrey; }
              .card {
                  /* Add shadows to create the "card" effect */
                  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                  transition: 0.3s;
                  padding: 1em;
                  background-color: White;
              }

              /* On mouse-over, add a deeper shadow */
              .card:hover {
                  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
              }

              /* Add some padding inside the card container */
              .container {
                  padding: 2px 16px;
              }
          </style>
    <!-- Page Content -->
    <div class="container" style="margin-top: 60px;">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="header">Latest Jobs:</h1>
            </div>
        </div>

    <div class="row">
      {% if latest_posting_list %}
        {% for post in latest_posting_list %}
        <div class="card">
            <div class="container">
              <h3>{{ post.post_title }}</h3>
              <h4>{{ post.post_date }}</h4>
              <p>{{ post.description }}</p>
              <a class="btn btn-primary"  href="{% url 'posting:detail' post.post_id %}">View Details
                <span class="glyphicon glyphicon-chevron-right"></span>
              </a>

          </div>
        </div>
          <hr>
        {% endfor %}
      {% else %}
        <div class="col-sm-12">
            <br>
            <a href="{% url 'posting:new_post' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Posting
                </button>
            </a>
        </div>
      {% endif %}
    </div>

</div>
{% endblock %}