sdnSite/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

###############################################################################
#   urlpatterns are the start of the chain fired off by django,
#   Use class_name.as_view() for class references from views.py, and use
#   views.method_name for method reference from views.py.
###############################################################################
urlpatterns = [
    # SDN.com/accounts/register/
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    # SDN.com/accounts/login_user/
    url(r'^login_user/$',views.LoginView.as_view(),name='login_user'),
    # SDN.com/accounts/logout_user
    url(r'^logout_user/$',views.LogoutView.as_view(),name='logout_user'),
	url(r'^upload_picture/$',views.uploadPicture,name='upload_picture'),
	url(r'^upload_resume/$',views.uploadResume,name='upload_resume'),
	# SDN.com/accounts/ ^(?P<profilename>)
    url(r'^$', views.AccountView.as_view(), name="account_page"),
]

sdnSite/home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # ex: /home/
    url(r'^$', views.IndexView.as_view(), name='index'),
    
]

sdnSite/posting/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.new_post, name="new_post"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^apply/$', views.application, name="application"),
    url(r'^congrats/$', views.congratulations, name="congrats"),
]

sdnSite/sdnSite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views
from posting import views
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^posting/', include('posting.urls', namespace='posting')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sdnSite/accounts/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Override of Django's user class to accomodate our needs can go here
# TODO: read up on django's built in methods that we can use to reduce work
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user')
    website = models.URLField(default='', blank=True)
    bio = models.TextField(default='', blank=True)
    phone = models.CharField(max_length=20, blank=True, default='')
    city = models.CharField(max_length=100, default='', blank=True)
    state = models.CharField(max_length=100, default='', blank=True)
    country = models.CharField(max_length=100, default='', blank=True)
    organization = models.CharField(max_length=100, default='', blank=True)
    resume = models.FileField(upload_to="resumes",default="resumes/hello.txt")
    picture = models.ImageField(upload_to="profile_pictures",default="profile_pictures/Happy_Toby.jpg")

    @receiver(post_save,sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)



class ProfilePicture(models.Model):
	picture = models.ImageField(upload_to="profile_pictures")

sdnSite/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, ProfilePicture

###############################################################################
# Forms in django are meant for building, displaying, and accepting info on models
# from models.py. Build form with relevant info based on model, then give the form
# to the form template inside the html page. This is how Django takes care of things
###############################################################################

class UserForm(forms.ModelForm):
    # passwords get protected
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta: # data to be grabbed in forms (relevant fields from models)
        model = User
        fields = ['username','email','password']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['website','bio','phone','city','state','country','organization']
        exclude = ['resume','picture']


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UploadResumeForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ['resume']
		exclude = ['user','website','bio','phone','city','country','organization','picture']
		
class UploadPictureForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ['picture']
		exclude = ['user','website','bio','phone','city','country','organization','resume']

class UploadFileForm(forms.ModelForm):

    class Meta:
        model = ProfilePicture
        fields = ['picture']

sdnSite/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import UserProfile, ProfilePicture
from django.http import JsonResponse
from django.db.models import Q
from .forms import UserForm, UploadFileForm, UserLoginForm, UploadResumeForm, UploadPictureForm
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy


# User account page
class AccountView(generic.DetailView):
    #TODO:find a way to load current logged in user (currently a non context page)
    model = User
    template_name = 'accounts/account.html'

    #user profile is loaded in account.html without context
    def get(self, request):
        profilename = request.user.username
        profile = UserProfile.objects.get(user__username=profilename)
        return render(request, self.template_name, {'profile' : profile})

# User creation
class UserFormView(View):
    form_class = UserForm
    template_name = 'accounts/registration_form.html'

    # display blank form for new user to fill out
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    # process form data when user submits
    def post(self, request):
        form = self.form_class(request.POST)

        # if form is complete and valid
        if form.is_valid():
            # save form data without changing database
            user = form.save(commit=False)

            # take in cleaned data (protected)
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']

            # set the pass word safely
            user.set_password(password)

            # commit changes to the database
            user.save()


            # for security, check that user is still valid
            if user is not None:

                # check that this user is active before logging in and sending away
                if user.is_active:
                    # login in and create session id
                    login(request, user)
                    # send to home
                    return redirect('home:index')


        # if this is where user ended up, their form wasnt valid.
        # so send them back with a message about what was wrong.
        return render(request, self.template_name, {'form':form})


# Create your method views here. -- these should be reconfigured to class views

def uploadResume(request):
	resumeForm = UploadResumeForm()
	if request.method=="POST":
		profilename = request.user.username
		profile = UserProfile.objects.get(user__username=profilename)
		resumeForm = UploadResumeForm(request.POST, request.FILES,instance=profile)
		if resumeForm.is_valid():
			resumeForm.save()
			return redirect('accounts:account_page')
		else:
			resumeForm = UploadResumeForm()
	return render(request,'accounts/profilepicture_form.html',{'form':resumeForm})

def uploadPicture(request):
	pictureForm = UploadPictureForm()
	if request.method=="POST":
		profilename = request.user.username
		profile = UserProfile.objects.get(user__username=profilename)
		pictureForm = UploadPictureForm(request.POST, request.FILES,instance=profile)
		if pictureForm.is_valid():
			pictureForm.save()
			return redirect('accounts:account_page')
		else:
			pictureForm = UploadPictureForm()
	return render(request,'accounts/profilepicture_form.html',{'form':pictureForm})

class LoginView(View):

    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = self.form_class(request.POST)

        # if form is complete and valid
        if form.is_valid():

            # take in cleaned data (protected)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # check that user doesnt already exist and name and pass are valid
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home:index')
                else:
                    return redirect('accounts/login.html')
            else:
                return redirect('accounts/login.html')

        return render(request, self.template_name, {'form':form})

class LogoutView(View):

    def get(self,request):
        logout(request)
        return redirect('home:index')




@login_required
def edit_user(request, pk):
    # querying the User object with pk from url
    user = User.objects.get(pk=pk)

    # prepopulate UserProfileForm with retrieved user values from above.
    user_form = UserForm(instance=user)

    # The sorcery begins from here, see explanation below
    ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=('website', 'bio', 'phone', 'city', 'country', 'organization'))
    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == "POST":
            user_form = UserForm(request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)

            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)

                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    return HttpResponseRedirect('/accounts/profile/')

        return render(request, "account/account_update.html", {
            "noodle": pk,
            "noodle_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied

# A dual use view, normal request gets login page, a POST request takes info and
#                   logs user in
def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('home/index.html')
            else:
                return render(request, 'accounts/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'accounts/login.html', {'error_message': 'Invalid login'})
    return render(request, 'accounts/login.html')

# This is a route to the login page, logging the user out upon arrival
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form" : form,
    }
    return render(request, 'accounts/login.html', context)

sdnSite/accounts/templates/accounts/account.html
{% extends 'accounts/base.html' %}
{% block title %}Account Page{% endblock %}

{% block body %}

<div class="container" style="margin-top: 60px;">
    <div class="span3 well">
        <center>
        <img src="{{ profile.picture.url }}" name="aboutme" width="140" height="140" class="img-circle">
        </a>
        <p><a href="{% url 'accounts:upload_picture' %}">Change Picture</a><p>
        <h2>{{ user.username }}</h2>
        <button type="submit" class="btn btn-success">Edit Account</button>

		    </center>
    </div>
    <div class="span3 well">
      <li>Resume: <a href="{{ profile.resume.url }}">{{ profile.resume.name }}</a> Change: <a href="{% url 'accounts:upload_resume' %}">Upload</a></li>
 		</li>
 		<li>Website: {% if profile.website %}
 			{{ profile.website }}
 		{% else %}
 			None
 		{% endif %}
 		</li>
 		<li>Biography:  {% if profile.bio %}
 			{{ profile.bio }}
 		{% else %}
 			None
 		{% endif %}
 		</li>
 		<li>Phone:  {% if profile.phone %}
 			{{ profile.phone }}
 		{% else %}
 			None
 		{% endif %}
 		</li>
 		<li>City:  {% if profile.city %}
 			{{ profile.city }}
 		{% else %}
 			None
		{% endif %}
  </li>
 		<li>Country:  {% if profile.country %}
 			{{ profile.country }}
 		{% else %}
 			None
 		{% endif %}
 		</li>
 		<li>Organization:  {% if profile.organization %}
 			{{ profile.organization }}
 		{% else %}
 			None
 		{% endif %}
 		</li>
    </div>

{% endblock %}

sdnSite/accounts/templates/accounts/base.html
<!-- This is the base html template used throughout the website, built on
     bootstrap. pages accessed with current user session will receive this navbar
     and page configuration -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SDN{% endblock %}</title>
    <!-- import django static files from ../static/ -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/main.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<style>
  body { background-color: LightGrey; }
</style>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home:index' %}">Freelance Connect</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                  <li>
                      <a href="{% url 'accounts:account_page' %}">My Account</a>
                  </li>
                  <li>
                      <a href="{% url 'posting:new_post' %}">Post</a>
                  </li>
                  <li>
                      <a href="{% url 'accounts:logout_user' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="{% block register_active %}{% endblock %}">
                    <a href="{% url 'accounts:register' %}">Sign Up</a>
                  </li>
                  <li class="{% block login_active %}{% endblock %}">
                    <a href="{% url 'accounts:login_user' %}">Log In</a>
                  </li>
                {% endif %}

              </ul>
              <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'home:index' %}">
               <div class="form-group">
                   <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
               </div>
               <button type="submit" class="btn btn-default">Search</button>
              </form>
              {% if user.is_authenticated %}
              <div class="pull-right">
                <ul class="nav pull-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{ user.username }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/user/preferences"><i class="icon-cog"></i> Preferences</a></li>
                            <li><a href="/help/support"><i class="icon-envelope"></i> Contact Support</a></li>
                            <li class="divider"></li>
                            <li><a href="/auth/logout"><i class="icon-off"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
              </div>
              {% endif %}
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>
  {% block body %}
  <!-- this is page specific html area -->
  {% endblock %}
</body>
</html>

sdnSite/accounts/templates/accounts/base_visitor.html
<!-- This is the visitor base html template used throughout the website, built on
     bootstrap. pages accessed without current user session will receive this navbar
     and page configuration -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SDN{% endblock %}</title>
    <!-- import django static files from ../static/ -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/main.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Software Developer Network</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}">
                  <a href="{% url 'accounts:register' %}">Sign Up</a>
                </li>
                <li class="{% block login_active %}{% endblock %}">
                  <a href="{% url 'accounts:login_user' %}">Log In</a>
                </li>
              </ul>
              <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'home:index' %}">
               <div class="form-group">
                   <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
               </div>
               <button type="submit" class="btn btn-default">Search</button>
              </form>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>
  {% block body %}
  <!-- this is page specific html area -->
  {% endblock %}
</body>
</html>

sdnSite/accounts/templates/accounts/file_form.html
<!-- This page will only be used in visitor context, so always extends base_visitor.html -->
{% extends 'accounts/base.html' %}
{% block title %}Upload File{% endblock %}
<!-- Tell django that user account is being registered -->
{% block register_active %}active{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
<div class="container-fluid">

    <div class="row">

      <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
          <div class="panel-body">

            <form class="form-horizontal" action="" method="post">
              <!-- Cross site request forgery protection, handled by Django -->
              {% csrf_token %}
              <!-- insert relevant form for registering user (based on forms.py) -->
              {% include 'accounts/form_template.html' %}
              <div class='form-group'>
                <div class='col-sm-offset-2 col-sm-10'>
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>

  </div>

</div>
{% endblock %}

sdnSite/accounts/templates/accounts/form_template.html
<!-- create a simple label and entry for each field of the form in use -->
<!-- leave space for an error on each field -->
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>

    <div class= "col-sm-10"><label class='control-label col-sm-2'>{{ field.label_tag }}</label>
    </div>
    <div class="col-sm-10">{{ field }}</div>
  </div>
  
{% endfor %}

sdnSite/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}

    <div class="container" style="margin-top: 40px;">
      <div class="col-lg-12">
    <div class="row">
        <div class="col-xs-4">

          <form class="form-signin" action="" method="post">

            {% csrf_token %}
            {% include 'accounts/form_template.html' %}
            <br>
            <button class="btn btn-sm btn-primary btn-block " style="text-align:center;" action="" type="submit">Sign in</button>

          </form>

        </div>
      </div>
    </div>

    </div> <!-- /container -->

{% endblock %}

sdnSite/accounts/templates/accounts/profilepicture_form.html
<!-- This page will only be used in visitor context, so always extends base_visitor.html -->
{% extends 'accounts/base.html' %}
{% block title %}Upload Picture{% endblock %}
<!-- Tell django that user account is being registered -->
{% block register_active %}active{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
<div class="container-fluid">

    <div class="row">

      <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
          <div class="panel-body">

            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              <!-- Cross site request forgery protection, handled by Django -->
              {% csrf_token %}
              <!-- insert relevant form for registering user (based on forms.py) -->
              {% include 'accounts/form_template.html' %}
              <div class='form-group'>
                <div class='col-sm-offset-2 col-sm-10'>
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>

  </div>

</div>
{% endblock %}

sdnSite/accounts/templates/accounts/registration_form.html
<!-- This page will only be used in visitor context, so always extends base_visitor.html -->
{% extends 'accounts/base.html' %}
{% block title %}Create Account{% endblock %}
<!-- Tell django that user account is being registered -->
{% block register_active %}active{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
<div class="container-fluid">

    <div class="row">

      <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
          <div class="panel-body">

            <form class="form-horizontal" action="" method="post">
              <!-- Cross site request forgery protection, handled by Django -->
              {% csrf_token %}
              <!-- insert relevant form for registering user (based on forms.py) -->
              {% include 'accounts/form_template.html' %}
              <div class='form-group'>
                <div class='col-sm-offset-2 col-sm-10'>
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>
          

          </div>
        </div>
      </div>

  </div>

</div>
{% endblock %}