sdnSite/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

###############################################################################
#   urlpatterns are the start of the chain fired off by django,
#   Use class_name.as_view() for class references from views.py, and use
#   views.method_name for method reference from views.py.
###############################################################################
urlpatterns = [
    # SDN.com/accounts/register/
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    # SDN.com/accounts/login_user/
    url(r'^login_user/$',views.LoginView.as_view(),name='login_user'),
    # SDN.com/accounts/logout_user
    url(r'^logout_user/$',views.LogoutView.as_view(),name='logout_user'),
	url(r'^upload_picture/$',views.uploadPicture,name='upload_picture'),
	url(r'^upload_resume/$',views.uploadResume,name='upload_resume'),
	# SDN.com/accounts/ ^(?P<profilename>)
    url(r'^$', views.AccountView.as_view(), name="account_page"),
]

sdnSite/home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # ex: /home/
    url(r'^$', views.IndexView.as_view(), name='index'),
    
]

sdnSite/posting/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.new_post, name="new_post"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^apply/$', views.application, name="application"),
    url(r'^congrats/$', views.congratulations, name="congrats"),
]

sdnSite/sdnSite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views
from posting import views
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^posting/', include('posting.urls', namespace='posting')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sdnSite/posting/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your models here.
class posting(models.Model):
    post_id = models.AutoField(primary_key=True)
	#employer_id = models.ForeignKey(Member, on_delete=models.CASCADE)

    post_title = models.CharField(default="", max_length=50)
    company_name = models.CharField(default="", max_length=30)
    description = models.CharField(default="", max_length=1000)
    total_pay = models.DecimalField(default=100, max_digits=50, decimal_places=2)
    #percent_up_front = models.DecimalField(default=25.00, max_digits=3, decimal_places=2)
    #status could be set up as a list of choices
    status = models.IntegerField(default=0)
    finish_date = models.DateField(default=timezone.now)
    post_date = models.DateField(default=timezone.now)
    tags = models.ManyToManyField('home.Tag')

    def get_absolute_url(self):
        return reverse('posting:detail', kwargs={'pk': self.post_id})

    def __str__(self):
        return self.post_title

class Post_Tag(models.Model):
	job_id = models.ForeignKey(posting,on_delete=models.CASCADE)
	skill_id = models.ForeignKey('home.Tag',on_delete=models.CASCADE)

sdnSite/posting/forms.py
from django import forms
from .models import posting
from django.forms.extras import SelectDateWidget
from django.forms.widgets import CheckboxSelectMultiple
from django.utils.translation import ugettext_lazy as _
###############################################################################
# Forms in django are meant for building, displaying, and accepting info on models
# from models.py. Build form with relevant info based on model, then give the form
# to the form template inside the html page. This is how Django takes care of things
###############################################################################

class PostingForm(forms.ModelForm):

    class Meta:
        model = posting
        exclude = ['post_id','post_date', 'status']
        #description = forms.CharField( widget=forms.TextArea)
        #finish_date = forms.DateField(widget=forms.SelectDateWidget())
        widgets = {
            'finish_date': SelectDateWidget(attrs={'style': 'width:10.5%'}),
            'description': forms.Textarea(attrs={'placeholder': 'Job Description', 'cols': 50, 'rows': 10}),
            'post_title': forms.Textarea(attrs={'cols': 50, 'rows': 1}),
            'company_name': forms.Textarea(attrs={'cols': 50, 'rows': 1}),
            'total_pay': forms.NumberInput(attrs={'step': 100, 'style': 'width:50ch'}),
            #'percent_up_front': forms.NumberInput(attrs={'step': 5, 'style': 'width:50ch'}),
            'tags': forms.SelectMultiple(attrs={'style': 'width:50ch'})
            #'tags': CheckboxSelectMultiple()
        }
        labels = {
            "description": _("Job Description")
        }
        help_texts = {
            'description': _("geeeererrrerr")
        }

sdnSite/posting/views.py
from django.shortcuts import render, HttpResponse
from .forms import PostingForm
from django.views import generic
from django.views.generic import View
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from .models import posting
from django.contrib.admin.widgets import AdminDateWidget
# Create Posting page
# class PostingCreate(generic.CreateView):
#     model = posting
#     #put relevant fields to be displayed here
#     fields = ['post_id','post_title', 'company_name', 'description', 'total_pay', 'finish_date', 'tags']
#     class Meta:
#         widgets = {
#             'finish_date': AdminDateWidget()
#         }



class DetailView(DetailView):
    model = posting
    template_name = 'posting/detail.html'

def new_post(request):
    if request.method == "POST":
        form = PostingForm(request.POST)
    else:
        form = PostingForm()
    if form.is_valid():
        posting = form.save(commit=False)
        posting.save()

    return render(request, 'posting/posting_form.html', {'form':form})

def application(request):
    return render(request, 'posting/application.html')

def congratulations(request):
    return render(request, 'posting/congratulations.html')

sdnSite/posting/templates/posting/agreement.html
<!--  -->


{% extends 'home/base.html' %}

{% block title %}Contractual Agreement{% endblock %}
{% block index_active %}active{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
    <!-- Page Content -->
	
    <p> Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam  eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?

 At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat</p>
 <button type="button">I Agree</button>
 
{% endblock %}

sdnSite/posting/templates/posting/application.html
{% extends 'posting/base.html' %}

{% block title %}Agreement{% endblock %}
<!-- Tell django that user account is being registered -->
{% block register_active %}active{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
<div class="container-fluid">




      <h2>Contract Agreement:</h2>
</div>
<div style="width:1200px; height:600px; overflow:scroll; padding:20px; border:10px solid">
      <center>
      <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In laoreet consectetur nulla, suscipit dapibus mi dictum a. In tristique felis at mi posuere auctor. Curabitur eleifend ex id placerat pharetra. Donec eget nulla convallis dui dignissim posuere. Vivamus ultrices consequat lacus. Morbi porttitor diam in sapien fringilla, ut mattis justo dictum. Vivamus vel efficitur velit. Etiam eget cursus dui. Suspendisse non venenatis nibh.

Nullam malesuada libero at mauris egestas, vitae tempor ligula gravida. Vestibulum vitae viverra est. Phasellus venenatis nisl sed tortor elementum cursus. Quisque eleifend elementum massa non pulvinar. Duis ut gravida metus, ac faucibus ligula. Nam interdum, tortor nec maximus condimentum, urna arcu ultrices purus, id egestas sapien libero in eros. Sed porta sem in pulvinar cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce fringilla sollicitudin nulla. Suspendisse quis rhoncus turpis. Fusce varius cursus dolor lacinia congue. Phasellus quam sapien, lobortis feugiat purus nec, varius semper arcu. Nullam orci ex, mattis facilisis diam eget, pellentesque lobortis libero. Suspendisse sapien neque, tempus eu mauris vitae, posuere iaculis tortor. Cras venenatis neque urna, nec suscipit nisi dapibus ac. Vestibulum ac ultricies ex, pretium feugiat dolor.

Nulla a fringilla nulla. Nam egestas risus nec vestibulum porta. Pellentesque malesuada, urna volutpat blandit iaculis, augue nulla dictum arcu, iaculis tincidunt lectus magna ut nunc. Morbi tempor scelerisque est, quis blandit turpis. Quisque interdum magna ut nibh maximus viverra. Nunc et massa viverra, feugiat massa sit amet, faucibus metus. Phasellus viverra at metus ac dapibus. Mauris eu hendrerit turpis, a finibus est. Nam at magna ut ante consectetur fringilla nec ac orci. Nulla blandit quam at tortor fringilla suscipit. Integer convallis consequat finibus. Integer fringilla maximus lorem, ut egestas libero faucibus eu.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar tortor at felis suscipit viverra. Quisque commodo sit amet neque eu mattis. Nulla facilisi. Aenean pulvinar sagittis arcu, id ullamcorper est placerat ac. Suspendisse tincidunt mauris id consectetur tincidunt. In semper id lacus lobortis tincidunt. Vivamus volutpat ac odio a ultricies. Pellentesque nisl augue, varius non velit id, viverra ornare tortor. Pellentesque eget sem vitae sem laoreet sodales. Integer rhoncus porttitor lacinia. In sed elit lorem. Praesent porttitor metus eu lectus posuere, et viverra erat faucibus.

Proin ipsum nulla, mattis viverra cursus a, fringilla condimentum nisi. Vivamus sit amet dui nec tortor fringilla dignissim. Sed sed venenatis leo, a bibendum diam. Donec in egestas diam. Maecenas ullamcorper metus sit amet neque facilisis, in rhoncus risus pharetra. Fusce congue mattis hendrerit. Proin euismod risus a mi viverra dapibus. Duis sem nunc, iaculis id tincidunt a, auctor vitae risus. Phasellus feugiat nulla ac suscipit accumsan. Vestibulum consectetur, lorem in congue pellentesque, justo dolor maximus dolor, lobortis viverra ante leo eu lacus. Vestibulum quis scelerisque dui. Pellentesque eget orci ligula. Donec malesuada purus ac ipsum fermentum, gravida consectetur neque tempus. Proin luctus sem justo, quis tempus augue aliquam eget. Nam luctus, purus eu porttitor blandit, arcu lorem rutrum turpis, sed accumsan quam erat sit amet tortor. Ut in convallis tortor.</h3>

</div>

<div style="padding:10px">
<a href="{% url 'posting:congrats' %}">
    <button type="button" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span>&nbsp; I Agree
    </button>
</div>
</a>
</center>




</div>
{% endblock %}

sdnSite/posting/templates/posting/base.html
<!-- This is the base html template used throughout the website, built on
     bootstrap. pages accessed with current user session will receive this navbar
     and page configuration -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SDN{% endblock %}</title>
    <!-- import django static files from ../static/ -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/main.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<style>
 body { background-color: LightGrey;
        padding-top: 70px;}
</style>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home:index' %}">Freelance Connect</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                  <li>
                      <a href="{% url 'accounts:account_page' %}">My Account</a>
                  </li>
                  <li>
                      <a href="{% url 'posting:new_post' %}">Post</a>
                  </li>
                  <li>
                      <a href="{% url 'accounts:logout_user' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="{% block register_active %}{% endblock %}">
                    <a href="{% url 'accounts:register' %}">Sign Up</a>
                  </li>
                  <li class="{% block login_active %}{% endblock %}">
                    <a href="{% url 'accounts:login_user' %}">Log In</a>
                  </li>
                {% endif %}

              </ul>
              <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'home:index' %}">
               <div class="form-group">
                   <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
               </div>
               <button type="submit" class="btn btn-default">Search</button>
              </form>
              <div class="pull-right">
                <ul class="nav pull-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{ user.username }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/user/preferences"><i class="icon-cog"></i> Preferences</a></li>
                            <li><a href="/help/support"><i class="icon-envelope"></i> Contact Support</a></li>
                            <li class="divider"></li>
                            <li><a href="/auth/logout"><i class="icon-off"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
              </div>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>
  <center>
  {% block body %}
  <!-- this is page specific html area -->
  {% endblock %}
</center>
</body>
</html>

sdnSite/posting/templates/posting/congratulations.html
<!--  -->


{% extends 'home/base.html' %}

{% block title %}Congratulations!{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
    <!-- Page Content -->
		<style>
			body { padding-top: 70px;
						 background-color: LightGrey; }
		</style>
		<center>
    <h1> Welcome to Freelance Connect!  Let's work together!</h1>
		<a href="{% url 'home:index' %}">
				<button type="button" class="btn btn-success">
						<span class="glyphicon glyphicon-plus"></span>&nbsp; Start Work
				</button>
		</a>
	</center>

{% endblock %}

sdnSite/posting/templates/posting/detail.html
{% extends 'posting/base.html' %}

{% block posting_active %}active{% endblock %}
{% block body %}
<div class="container" style="margin-top: 60px;">
  <center>
  <h1>{{ posting.post_title }} </h1>
  {% if posting.status == 1 %}
    <h3>This job is available</h3>
  {% endif %}
  <h3>${{posting.total_pay}}
  <h3>{{ posting.description }}</h3>
  <a href="{% url 'posting:application' %}">
      <button type="button" class="btn btn-success">
          <span class="glyphicon glyphicon-plus"></span>&nbsp; Apply
      </button>
  </a>
</center>
</div>





{% endblock %}

sdnSite/posting/templates/posting/form_template.html
<!-- create a simple label and entry for each field of the form in use -->
<!-- leave space for an error on each field -->
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>

    <label class='control-label'>{{ field.label_tag }}</label>
    <div class="col-sm-2 col-md-12 inputlg">{{ field }}</div>
  </div>
{% endfor %}

sdnSite/posting/templates/posting/posting_form.html
<!-- This page will only be used in visitor context, so always extends base_visitor.html -->

{% extends 'posting/base.html' %}

{% block title %}Create Posting{% endblock %}
<!-- Tell django that user account is being registered -->
{% block register_active %}active{% endblock %}

<!-- start block body, this is what is inserted into base_visitor.html -->
{% block body %}
<center>
<div class="container-fluid">

    <div class="row">

      <div class="col-sm-12 col-md-10 col-md-offset-1">
        <div class="panel panel-default">
          <div class="panel-body">

            <form class="form-horizontal center" action="" method="post">
              <!-- Cross site request forgery protection, handled by Django -->
              <h1>Create Job</h1>
              {% csrf_token %}
              <!-- insert relevant form for registering user (based on forms.py) -->
              {% include 'posting/form_template.html' %}
              <div class='form-group'>
                <div class='col-offset-6 col-6'>
                  <button type="submit" class="btn btn-success btn-lg">Submit</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>

  </div>

</div>
</center>
{% endblock %}